### PR TITLE
Added zig-nanoid to awesome list.

### PR DESCRIPTION
**Pull request by SasLuca**

### CODE REVIEW

**Comment by catdevnull** [comment]
Thanks for the contribution! Just left one tiny suggestion.

**Comment by SasLuca** [comment]
What exactly is the tiny suggestion? I can't seem to find any other notes or comments you might have made.

**Comment by catdevnull** [comment]
Ugh, I don't know..

image

I don't use GitHub often. Basically, removing the 'A ' at the start as it is unnecesary. I was pretty sure it was against [Awesome guidelines](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md) but I can't find anything about it.

Thanks again for contributing!

**Comment by SasLuca** [comment]
Ah, I see, for some reason, your review does not display to me.
Other items also included in that category use "A" at the start but I have no issue with removing it.
image

**Comment by catdevnull** [comment]
You're right, sorry.

**Pull request merged**
